# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
 
  config.vm.box = "bento/fedora-29"
  config.vm.box_version = "201812.27.0"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  
    vb.memory = "4096"
    vb.cpus = "4"
    # fix the issue failed to switch graphic mode with error Failed to set CRTC mode  29  Invalid argument gnome-shell virtualbox
    # https://forums.virtualbox.org/viewtopic.php?f=3&t=90372
    # https://stackoverflow.com/questions/24231620/how-to-set-vagrant-virtualbox-video-memory
    vb.customize ["modifyvm", :id, "--vram", "32"]
  end
  
  ### bootstrap (fixes) https://github.com/darkn3rd/hello_web/blob/master/vagrant-ansible/fedora-28/Vagrantfile  ###
  config.vm.provision "shell",
    inline: "/usr/bin/dnf install -y libselinux-python"
	
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
